server:
  port: 8080

spring:
  application:
    name: gateway-server # application name
  cloud:
    gateway:
      # routing rules
      routes:
        - id: product-service           #route id unique
          uri: http://localhost:8081/   #target uri
          predicates:
            - Path=/product/**
           # - Query=token, abc.